---

services:
  routeros:
    image: mnazarenko/docker-routeros:${ROUTEROS_VERSION:-latest}
    environment:
      DEBUG: "N"
      DISPLAY: "web"
    ports:
      - 127.0.0.1:8728:8728
      - 127.0.0.1:2222:22
      - 127.0.0.1:8006:8006
      - 127.0.0.1:5900:5900
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - "NET_ADMIN"
    stop_grace_period: 20s

  wait-for-routeros:
    image: alpine
    entrypoint: ["/bin/sh"]
    command:
      - "-c"
      - >-
        echo "waiting for RouterOS to be up and running";
        for i in $(seq 1 60); do
          if nc -w1 -z routeros 8728; then
            exit 0;
          else
            printf ".";
            sleep 1;
          fi done;
          exit 1
