name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental: [false]
        go: ["1.18"]
        os: [ubuntu-latest]
        # Test against latest stable 6.x and 7.x and "latest" stable
        routeros: ["6.49.15", "7.14.3"]
        include:
          - experimental: true
            go: 1.18
            os: ubuntu-latest
            routeros: "latest"

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v .

      - name: Run linters
        run: make lint

      - name: Wait until RouterOS container is ready
        run: ./bin/wait-for-routeros.sh 127.0.0.1 8080

      - name: Run provider tests
        run: make testacc
        env:
          MIKROTIK_HOST: 127.0.0.1:8728
          MIKROTIK_USER: admin
          MIKROTIK_PASSWORD: ''
          TF_ACC: 1

      - name: Run client tests
        run: make testclient
        env:
          MIKROTIK_HOST: 127.0.0.1:8728
          MIKROTIK_USER: admin
          MIKROTIK_PASSWORD: ''
          TF_ACC: 1

    services:
      routeros:
        image: mnazarenko/docker-routeros:${{ matrix.routeros }}
        ports:
          - 8728:8728
          - 8080:80
        options: >-
          --cap-add=NET_ADMIN
          --device=/dev/net/tun
